name: Interact with ChatGPT

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate_code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - name: make the script file executable
        run: chmod +x scripts/script.sh
        
      - name: checkout the repository
        uses: actions/checkout@v2

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact

      - name: list files recursively
        run: ls -R autocoder-artifact
        
      - name: run the script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY
