name: Interact with ChatGPT

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate_code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Make Script Executable
        run: chmod +x scripts/script.sh

      - name: Run GPT Interaction Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: autocoder-artifact
          path: autocoder-bot

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: autocoder-artifact
          path: autocoder-artifact

      - name: List Files
        run: ls -R autocoder-artifact
