name: Interact with ChatGPT

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate_code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - name: make_the_script_file_executable
        run: chmod +x scripts/script.sh
        
      - name: checkout_the_repository
        uses: actions/checkout@v2

      - name: upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot

      - name: download_artifacts
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact

      - name: list_files_recursively
        run: ls -R autocoder-artifact
        
      - name: run_the_script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY
