name: Interact with ChatGPT

on:
  issues:
    types: [opened, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate_code:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: interact with ChatGPT
        uses: MorgunovE/AutoCoder@v1.0.7
        with:
          SCRIPT_PATH: ./scripts/script.sh
          LABEL: autocoder-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Make the script file executable
        run: chmod +x $GITHUB_ACTION_PATH/scripts/script.sh
        shell: bash

      - name: Run the script
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: "$GITHUB_ACTION_PATH/scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY"

      - name: Configure git
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"
        shell: bash

      - name: Commit changes
        run: |
          git add .
          git commit -m "Add generated code for issue #${{ github.event.issue.number }}"
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add generated code for issue #${{ github.event.issue.number }}"
          branch: autocoder-branch-${{ github.event.issue.number }}
          base: main
          title: "Add generated code for issue #${{ github.event.issue.number }}"
          body: "This pull request contains the generated code for issue #${{ github.event.issue.number }}."
          labels: autocoder-bot
